[env:denky32]
platform = espressif32
board = denky32
monitor_speed = 115200
test_framework=googletest
framework = arduino
board_build.partitions = huge_app.csv

lib_deps =
	knolleary/PubSubClient@^2.8
	adafruit/Adafruit GFX Library
	https://github.com/mrfaptastic/ESP32-HUB75-MatrixPanel-I2S-DMA.git
	https://github.com/plageoj/urlencode
	bblanchon/ArduinoJson@^7.2.2
	https://github.com/TartanLlama/expected

build_unflags =
	-std=gnu++11

build_flags =
	-std=gnu++17
	-Wall
	-Werror
