[env:denky32]
platform = espressif32
board = denky32
monitor_speed = 115200
test_framework=googletest
framework = arduino

lib_deps =
	knolleary/PubSubClient@^2.8
    google/googletest @ ^1.17.0
	adafruit/Adafruit GFX Library
	bodmer/TJpg_Decoder
	https://github.com/mrfaptastic/ESP32-HUB75-MatrixPanel-I2S-DMA.git
	bblanchon/ArduinoJson@^7.2.2

build_unflags =
	-std=gnu++11

build_flags =
	-std=gnu++17
	-Wall
	-Werror
